import { readFile, writeFile } from 'node:fs/promises';

// Generates an explicit manual recovery script; never connects to a database.
const reset = `-- DESTRUCTIVE: dedicated Living Room Cinema project only.
-- Deletes application tables/data and non-extension functions in public/private.
-- Keeps Auth users, Storage, Vault secrets, extensions, and cron schedules.
-- Existing host grants are deleted and must be re-added after this reset.
-- Generated by node scripts/prepare-reset.mjs. Run the ENTIRE file in SQL Editor.
begin;
set local lock_timeout = '5s';

do $reset$
declare item record;
begin
  -- Remove old RPCs/helpers first, including signatures from a different schema.
  -- CASCADE also removes application triggers that invoke these functions.
  for item in
    select n.nspname, p.proname, pg_get_function_identity_arguments(p.oid) as args
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname in ('public','private') and p.prokind in ('f','p')
      and not exists (select 1 from pg_depend d where d.classid='pg_proc'::regclass
        and d.objid=p.oid and d.deptype='e')
  loop
    execute format('drop routine if exists %I.%I(%s) cascade',item.nspname,item.proname,item.args);
  end loop;

  for item in
    select n.nspname,c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where n.nspname in ('public','private') and c.relkind in ('r','p')
      and not exists (select 1 from pg_depend d where d.classid='pg_class'::regclass
        and d.objid=c.oid and d.deptype='e')
  loop
    execute format('drop table if exists %I.%I cascade',item.nspname,item.relname);
  end loop;
end
$reset$;

`;
const files = ['supabase/migrations/202610020001_cinema.sql', 'supabase/migrations/202610020002_mail.sql', 'supabase/migrations/202610060001_fix_open_round.sql', 'supabase/seed.sql'];
const chunks = await Promise.all(files.map(async path => `-- Source: ${path}\n${await readFile(path,'utf8')}\n`));
await writeFile('supabase/reset-and-install.sql', reset + chunks.join('\n') + `
notify pgrst, 'reload schema';
select count(*) as seeded_movies from public.movies; -- Expected: 32
commit;
`);
console.log('Prepared supabase/reset-and-install.sql. No database was changed.');
