import { readFile, writeFile } from 'node:fs/promises';
import vm from 'node:vm';
const context = { window: {} };
vm.runInNewContext(await readFile('dist/movies.js','utf8'), context);
const quote = value => "'" + JSON.stringify(value).replaceAll("'", "''") + "'::jsonb";
const movies = context.window.MOVIES.map(({id,title,year,genres,description,poster,imdb,rt}) => ({id,title,year,genres,description,poster,imdb,rt}));
await writeFile('supabase/seed.sql', `-- Generated by node scripts/seed.mjs; only inserts missing catalog entries.\ninsert into public.movies(id,title,year,genres,description,poster,imdb,rt)\nselect id,title,year,genres,description,poster,imdb,rt\nfrom jsonb_to_recordset(${quote(movies)}) as m(id text,title text,year integer,genres text[],description text,poster text,imdb jsonb,rt jsonb)\non conflict(id) do nothing;\n`);
